title: Lineamientos de desarrollo
logo: /assets/img/logo.png
description: Lineamientos para del desarrollo de aplicaciones sobre el repositorio de la Dirección de Información y Tecnologías DSIT de la Universidad de Los Andes. Versión 1.1.2
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
