title: Guía de Desarrollo de Software
logo: /assets/img/logo.png
description: Guía de Desarrollo de Software para del desarrollo de aplicaciones sobre el repositorio de la Dirección de Información y Tecnologías DSIT de la Universidad de Los Andes. Versión 1.1.3
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
